namespace SamplePlugin.Plugins;

public enum LogMessageType
{
    ChatLog = 0,
    Territory = 1,
    ChangePrimaryPlayer = 2,
    AddCombatant = 3,
    RemoveCombatant = 4,
    PartyList = 11,
    PlayerStats = 12,
    StartsCasting = 20,
    ActionEffect = 21,
    AOEActionEffect = 22,
    CancelAction = 23,
    DoTHoT = 24,
    Death = 25,
    StatusAdd = 26,
    TargetIcon = 27,
    WaymarkMarker = 28,
    SignMarker = 29,
    StatusRemove = 30,
    Gauge = 31,
    World = 32,
    Director = 33,
    NameToggle = 34,
    Tether = 35,
    LimitBreak = 36,
    EffectResult = 37,
    StatusList = 38,
    UpdateHp = 39,
    ChangeMap = 40,
    SystemLogMessage = 41,
    StatusList3 = 42,
    Settings = 249,
    Process = 250,
    Debug = 251,
    PacketDump = 252,
    Version = 253,
    Error = 254
}
